name: Issue Template
description: Create an issue template for this repository

body:
  - type: input
    id: issue_title
    attributes:
      label: Issue Title
      description: Provide a brief title for the issue

  - type: dropdown
    id: tool_category
    attributes:
      label: Tool Category
      description: Select the category of the tool
      options:
        - Front-end Development
        - Back-end Development
        - Version Control
        - No-Code Tools
        - AI-Powered Tools
        - Design Assets

  - type: input
    id: tool_name
    attributes:
      label: Tool Name
      description: Insert the name of the tool

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: Select the type of issue
      options:
        - Bug Report
        - Feature Request
        - Documentation Improvement
        - Other

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the issue, including any relevant context, error messages, or screenshots

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (if applicable)
      description: Describe the steps necessary to reproduce the issue
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior (if applicable)
      description: Describe what you expected to happen

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior (if applicable)
      description: Describe what actually happened

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information (if applicable)
      description: Provide any additional details that might be helpful
      placeholder: |
        - **Operating System**: Insert OS
        - **Browser**: Insert browser
        - **Version**: Insert version

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
